version: '3.3'
services:
  buildprocess:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/stijnbaltessen.digital/fullchain.pem:/etc/ssl/stijnbaltessen.digital/fullchain.pem
      - /etc/letsencrypt/live/stijnbaltessen.digital/privkey.pem:/etc/ssl/stijnbaltessen.digital/privkey.pem