version: "3.7"
services:
    nginx-reverse-proxy:
        container_name: reverse-proxy
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            "80:80"
            "443: 443"
