version: '3.3'
services:
  buildprocess:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/stijnbaltessen.digital:/etc/ssl/stijnbaltessen.digital